#!/usr/bin/env python3
"""
Prometheus Metrics Exporter for Gemini 3.1 Pro Oracle
Tracks token usage, thinking latency, and performance metrics for enterprise monitoring
"""

from prometheus_client import start_http_server, Counter, Gauge, Histogram, Info
import time
import threading
import os
from typing import Optional, Dict, Any

# Core Metrics for Gemini 3.1 Pro Oracle
TOKENS_INPUT = Counter(
    'oracle_tokens_input_total',
    'Total input tokens consumed by Gemini 3.1 Pro',
    ['session_id', 'model']
)

TOKENS_OUTPUT = Counter(
    'oracle_tokens_output_total',
    'Total output tokens generated by Gemini 3.1 Pro',
    ['session_id', 'model']
)

TOKENS_THINKING = Counter(
    'oracle_tokens_thinking_total',
    'Total tokens used for Deep Think Mini reasoning',
    ['session_id', 'model']
)

THINKING_LATENCY = Histogram(
    'oracle_thinking_duration_seconds',
    'Time spent in Deep Think Mini state',
    ['session_id', 'model', 'thinking_level'],
    buckets=[5, 10, 15, 30, 45, 60, 90, 120]
)

API_REQUESTS = Counter(
    'oracle_api_requests_total',
    'Total API requests to Gemini 3.1 Pro',
    ['session_id', 'model', 'status']
)

SESSION_DURATION = Histogram(
    'oracle_session_duration_seconds',
    'Duration of active reasoning sessions',
    ['session_id'],
    buckets=[60, 300, 600, 1800, 3600]
)

DATABASE_SIZE = Gauge(
    'oracle_database_size_bytes',
    'Size of the Oracle state database in bytes'
)

ACTIVE_SESSIONS = Gauge(
    'oracle_active_sessions',
    'Number of currently active sessions'
)

# Cost tracking (based on 2026 pricing)
COST_ESTIMATE = Counter(
    'oracle_cost_estimate_dollars',
    'Estimated cost in USD for API usage',
    ['currency']
)

# System health metrics
SERVICE_UPTIME = Gauge(
    'oracle_service_uptime_seconds',
    'Oracle service uptime in seconds'
)

MEMORY_USAGE = Gauge(
    'oracle_memory_usage_bytes',
    'Current memory usage of Oracle process'
)

# Info metrics for configuration tracking
ORACLE_INFO = Info(
    'oracle_build_info',
    'Oracle system information',
    ['version', 'model', 'thinking_level']
)

class OracleMetrics:
    """
    Prometheus metrics exporter for Gemini 3.1 Pro Oracle monitoring.
    Tracks token usage, thinking latency, and system performance.
    """

    def __init__(self, port: int = 8000, session_id: str = "default"):
        """
        Initialize the metrics exporter.

        Args:
            port: Port to expose Prometheus metrics
            session_id: Current session identifier
        """
        self.port = port
        self.session_id = session_id
        self.model_name = "gemini-3.1-pro-preview-customtools"
        self.thinking_level = os.environ.get("THINKING_LEVEL", "HIGH")

        # Start Prometheus HTTP server
        start_http_server(port)

        # Set static info
        ORACLE_INFO.info({
            'version': '3.1.0',
            'model': self.model_name,
            'thinking_level': self.thinking_level
        })

        # Track service start time for uptime
        self.start_time = time.time()

        print(f"[*] Prometheus Exporter active on port {port}")
        print(f"[*] Model: {self.model_name}")
        print(f"[*] Thinking Level: {self.thinking_level}")
        print(f"[*] Session ID: {self.session_id}")

        # Start background monitoring thread
        self.monitoring_thread = threading.Thread(target=self._background_monitoring)
        self.monitoring_thread.daemon = True
        self.monitoring_thread.start()

    def track_api_call(self, response: Any, duration: float, status: str = "success"):
        """
        Track an API call to Gemini 3.1 Pro.

        Args:
            response: Gemini API response object
            duration: Time spent in API call (seconds)
            status: Call status ('success', 'error', 'timeout')
        """
        try:
            # Extract usage metadata from response
            if hasattr(response, 'usage_metadata') and response.usage_metadata:
                meta = response.usage_metadata

                # Track input tokens
                if hasattr(meta, 'prompt_token_count'):
                    TOKENS_INPUT.labels(
                        session_id=self.session_id,
                        model=self.model_name
                    ).inc(meta.prompt_token_count)

                # Track output tokens
                if hasattr(meta, 'candidates_token_count'):
                    TOKENS_OUTPUT.labels(
                        session_id=self.session_id,
                        model=self.model_name
                    ).inc(meta.candidates_token_count)

                # Track thinking tokens (3.1 Pro specific)
                if hasattr(meta, 'thoughts_token_count'):
                    TOKENS_THINKING.labels(
                        session_id=self.session_id,
                        model=self.model_name
                    ).inc(meta.thoughts_token_count)

                # Estimate cost (2026 pricing)
                self._update_cost_estimate(meta)

            # Track thinking latency
            THINKING_LATENCY.labels(
                session_id=self.session_id,
                model=self.model_name,
                thinking_level=self.thinking_level
            ).observe(duration)

            # Track API requests
            API_REQUESTS.labels(
                session_id=self.session_id,
                model=self.model_name,
                status=status
            ).inc()

        except Exception as e:
            print(f"[!] Metrics tracking error: {e}")

    def update_session_duration(self, duration: float):
        """
        Track session duration.

        Args:
            duration: Session duration in seconds
        """
        SESSION_DURATION.labels(session_id=self.session_id).observe(duration)

    def update_database_metrics(self, db_size: int, active_sessions: int):
        """
        Update database-related metrics.

        Args:
            db_size: Database size in bytes
            active_sessions: Number of active sessions
        """
        DATABASE_SIZE.set(db_size)
        ACTIVE_SESSIONS.set(active_sessions)

    def _update_cost_estimate(self, usage_metadata: Any):
        """
        Estimate API costs based on 2026 pricing.

        Args:
            usage_metadata: Gemini usage metadata
        """
        try:
            cost = 0.0

            # Input tokens: $2 per 1M
            if hasattr(usage_metadata, 'prompt_token_count'):
                cost += (usage_metadata.prompt_token_count / 1_000_000) * 2.0

            # Output tokens: $12 per 1M
            if hasattr(usage_metadata, 'candidates_token_count'):
                cost += (usage_metadata.candidates_token_count / 1_000_000) * 12.0

            # Thinking tokens: $12 per 1M (same as output)
            if hasattr(usage_metadata, 'thoughts_token_count'):
                cost += (usage_metadata.thoughts_token_count / 1_000_000) * 12.0

            COST_ESTIMATE.labels(currency="USD").inc(cost)

        except Exception as e:
            print(f"[!] Cost calculation error: {e}")

    def _background_monitoring(self):
        """
        Background thread for monitoring system metrics.
        """
        import psutil

        while True:
            try:
                # Update uptime
                SERVICE_UPTIME.set(time.time() - self.start_time)

                # Update memory usage
                process = psutil.Process()
                MEMORY_USAGE.set(process.memory_info().rss)

                # Sleep for 30 seconds before next update
                time.sleep(30)

            except Exception as e:
                print(f"[!] Background monitoring error: {e}")
                time.sleep(60)  # Wait longer on error

    def get_metrics_summary(self) -> Dict[str, Any]:
        """
        Get a summary of current metrics.

        Returns:
            Dictionary with current metric values
        """
        return {
            "session_id": self.session_id,
            "model": self.model_name,
            "thinking_level": self.thinking_level,
            "uptime_seconds": time.time() - self.start_time,
            "port": self.port
        }

    def should_switch_to_medium(self) -> bool:
        """
        Check if we should switch to MEDIUM thinking level based on usage.

        Returns:
            True if switch is recommended
        """
        try:
            # Get current thinking tokens
            thinking_metrics = TOKENS_THINKING._metrics
            session_key = (self.session_id, self.model_name)

            if session_key in thinking_metrics:
                thinking_count = thinking_metrics[session_key]._value.get()
                # Switch if thinking tokens exceed 80% of typical output limit
                return thinking_count > (65536 * 0.8)
            else:
                return False

        except Exception as e:
            print(f"[!] Thinking level check error: {e}")
            return False


# Global metrics instance
class MetricsManager:
    """Singleton manager for OracleMetrics instances."""
    _instance: Optional[OracleMetrics] = None

    @classmethod
    def get_oracle_metrics(cls) -> OracleMetrics:
        """Get or create the global OracleMetrics instance."""
        if cls._instance is None:
            session_id = os.environ.get("ORACLE_SESSION_ID", "default")
            port = int(os.environ.get("METRICS_PORT", "8000"))
            cls._instance = OracleMetrics(port=port, session_id=session_id)
        return cls._instance

def get_oracle_metrics() -> OracleMetrics:
    """Get or create the global OracleMetrics instance."""
    return MetricsManager.get_oracle_metrics()

def track_oracle_response(response: Any, duration: float, status: str = "success"):
    """
    Convenience function to track an Oracle API response.

    Args:
        response: Gemini API response object
        duration: Time spent in API call
        status: Call status
    """
    metrics = get_oracle_metrics()
    metrics.track_api_call(response, duration, status)

if __name__ == "__main__":
    # Standalone metrics server for testing
    import sys

    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8000
    session_id = sys.argv[2] if len(sys.argv) > 2 else "standalone"

    print(f"[*] Starting Oracle Metrics Exporter")
    print(f"[*] Port: {port}")
    print(f"[*] Session: {session_id}")

    metrics = OracleMetrics(port=port, session_id=session_id)

    # Keep running
    try:
        while True:
            time.sleep(60)
            summary = metrics.get_metrics_summary()
            print(f"[+] Metrics active: {summary}")

    except KeyboardInterrupt:
        print("\n[!] Metrics exporter stopped")
